### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by gertjanmaas** [philips-labs/docker-action#1]
Code has been pushed to master and tested with another repository. Please review this code.

**Comment by npalm** [comment]
Nice work! Just a few thoughts

- No description how to create a release. Ideas add commit hook to run yarn build, or maybe solve in an action
- Maybe add a test with `INPUT_LATESTBRANCH` set to `develop`
- Maybe add a debug (core.debug) statement to the function `getDockerTag`

**Comment by JeroenKnoops** [comment]
I guess this can be closed?
